---
- hosts: localhost
  name: Install Software for realm and Samba
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Install packages for Realm
      package:
        name:
          - realmd
          - sssd
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - samba-common-tools
          - krb5-workstation
          - samba
          - samba-client
          - samba-winbind
          - samba-winbind-clients
        state: latest