---
- hosts: localhost
  name: Create Storage for share
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: create partion on device
      parted:
       device: "{{ device }}"
       number: 1
       flags: [ lvm ]
       state: present

    - name: create volume group
      lvg:
       vg: "vg.{{ sharename }}"
       pvs: "{{ device }}1"

    - name: create logical transport disk on vg
      lvol:
       vg: "vg.{{ sharename }}"
       lv: "lv.{{ sharename }}"
       size: 100%FREE

    - name: create filesystem xfs on lv
      filesystem:
       fstype: xfs
       dev: "/dev/mapper/vg.{{ sharename }}-lv.{{ sharename }}"

    - name: create directory for lv
      file:
       path: "{{ sharepath }}"
       state: directory

    - name: add fstab entry
      mount:
       name: "{{ sharepath }}"
       src: "/dev/mapper/vg.{{ sharename }}-lv.{{ sharename }}"
       fstype: xfs
       opts: defaults
       state: present

    - name: mount disk
      shell: mount -a
      args:
       warn: false