---
- hosts: localhost
  name: Configure Samba
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - ../vars.yml

  tasks:
    - name: Enable SMB in firewall
      firewalld:
        service: samba
        permanent: true
        state: enabled
      notify: reload firewall

    - name: Set SELinux for share chcon
      command: chcon -R -t samba_share_t "{{ sharepath }}"

    - name: Allow Samba to modify files in share
      community.general.sefcontext:
        target: '{{ sharepath }}(/.*)?'
        setype: samba_share_t
        state: present

    - name: Configure Samba
      template:
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload smb

    - name: Configure Krb5
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable Smb Service
      systemd:
        name: smb
        state: started
        enabled: yes

    - name: Enable Nmb Service
      systemd:
        name: nmb
        state: started
        enabled: yes

  handlers:
    - name: reload firewall
      systemd:
        name: firewalld
        state: reloaded

    - name: reload smb
      systemd:
        name: smb
        state: reloaded