---
- hosts: localhost
  name: Configure Samba
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - ../vars.yml

  tasks:
    - name: Install packages for Samba
      dnf:
        name:
          - samba
          - samba-client
        state: latest

    - name: Enable Smb Service
      systemd:
        name: smb
        state: started
        enabled: yes

    - name: Enable Nmb Service
      systemd:
        name: nmb
        state: started
        enabled: yes

    - name: Enable Winbind Service
      systemd:
        name: winbind
        state: started
        enabled: yes

    - name: Enable SMB in firewall
      firewalld:
        service: samba
        permanent: true
        state: enabled
      notify: reload firewall

    - name: Set SELinux for /mnt/transport chcon
      command: chcon -R -t samba_share_t /mnt/transport

    - name: Allow Samba to modify files in /mnt/transport
      community.general.sefcontext:
        target: '/mnt/transport(/.*)?'
        setype: samba_share_t
        state: present

    - name: Configure Samba
      template:
        src: smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
      notify: reload smb

    - name: Configure Krb5
      template:
        src: krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configure sssd
      template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: '0600'

  handlers:
    - name: reload firewall
      systemd:
        name: firewalld
        state: reloaded

    - name: reload smb
      systemd:
        name: smb
        state: reloaded