---
- hosts: localhost
  name: Configure Samba
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - ../vars.yml

  tasks:
    - name: Configure sssd
      template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: '0600'
      notify: reload sssd

    - name: Flush handlers
      meta: flush_handlers

    - name: Enable Smb Service
      systemd:
        name: smb
        state: started
        enabled: yes

    - name: Enable Nmb Service
      systemd:
        name: nmb
        state: started
        enabled: yes

    - name: Enable Winbind Service
      systemd:
        name: winbind
        state: started
        enabled: yes

    - name: Set acl on share
      ansible.builtin.file:
        path: "{{ sharepath }}"
        owner: administrator
        group: "{{ accessgroup }}"
        mode: '0770'

  handlers:
    - name: reload sssd
      systemd:
        name: sssd
        state: restarted