---
- hosts: localhost
  name: Install and configure realm and Samba
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
    - ../vars2.yml

  roles:
    - jesperberth.el_domain_join
    - jesperberth.el_samba_realm
    - jesperberth.el_datadisk
